### ISSUE TITLE
睡眠正常吗

### ISSUE THREAD

**Issue by Deeachain** [athlonreg/Thunderobot-G7000S-9300H#1]
Hi，你的睡眠正常吗，我的雷神笔记本睡眠后键盘灯亮，风扇还在转，唤醒不了。

**Comment by ColorDreams** [comment]
> Hi，你的睡眠正常吗，我的雷神笔记本睡眠后键盘灯亮，风扇还在转，唤醒不了。

我的机器没问题。如果你的笔记本没办法正常休眠，那就检查一下电池是否已经修补，一般都是电池有问题才会导致无法正常休眠的。

**Comment by Deeachain** [comment]
谢谢你的解答，我试一试
